name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish-cli:
    runs-on: ubuntu-latest
    env:
      # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get the latest version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Run cross-build
        run: make cross-build
      - name: Run compress binary
        run: make compress
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
      - name: Upload Linux amd64 tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-linux-amd64.tar.gz
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-linux-amd64.tar.gz
          asset_content_type: binary/octet-stream
      - name: Upload Linux amd64 zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-linux-amd64.zip
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-linux-amd64.zip
          asset_content_type: binary/octet-stream
      - name: Upload MacOS tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-darwin-amd64.tar.gz
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.tar.gz
          asset_content_type: binary/octet-stream
      - name: Upload MacOS zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-darwin-amd64.zip
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-darwin-amd64.zip
          asset_content_type: binary/octet-stream
      - name: Upload Windows tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-windows-amd64.tar.gz
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-windows-amd64.tar.gz
          asset_content_type: binary/octet-stream
      - name: Upload Windows zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/derrick-windows-amd64.zip
          asset_name: derrick-${{ steps.get_version.outputs.VERSION }}-windows-amd64.zip
          asset_content_type: binary/octet-stream
      - name: Upload Checksums
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./_bin/sha256sums.txt
          asset_name: sha256sums.txt
          asset_content_type: text/plain
